apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-dev
  namespace: development
  labels:
    prometheus: prometheus-dev
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector: 
    matchLabels: {}
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
