apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: development
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: "metrics"  # Corrected from "9133"
      path: /metrics
      interval: 30s
