apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: development
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"  # Change this password
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: development
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
