apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: development
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /nginx_status {
            stub_status;
            allow all;
        }
    }
